baseURL = "http://example.org/"
languageCode = "en-us"
title = "Wes Dingman"
theme = "introduction"

[params]
    favicon                      = "/img/favicon.ico"          # Path to favicon file
 
 # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://github.com/wjdingman1/"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/wes-dingman-628026187/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:wjdingman1@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"

    [params.home]
        numberOfProjectsToShow   = 2                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        

     [params.projects]
        useTwoColumns            = true                  # Use a layout with two columns instead of three

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "friendly"
    tabWidth = 4

